Switch to uv for development + update dev deps

diff --git a/init_dev_env b/init_dev_env
--- a/init_dev_env
+++ b/init_dev_env
@@ -1,54 +1,52 @@
-#!/bin/bash
+#!/usr/bin/env bash
+#
+# Copyright 2009-2024 Joshua Bronson. All rights reserved.
+#
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+# shellcheck disable=SC1091
 
 set -euo pipefail
 
-# Keep in sync with _default_py_minor_ver in ./tox.ini and ./upgrade-dev-dependencies:
-declare -r _default_py_minor_ver="12"
-export DEV_PY="python3.$_default_py_minor_ver"
-
 declare -r hint="Hint: Use 'nix develop' to bootstrap a development environment"
 
-if ! type "$DEV_PY"; then
-  >&2 echo "Error: No $DEV_PY on PATH. $hint"
-  exit 1
-fi
+source ./dev-deps/py_ver.env
 
-if ! type pre-commit; then
-  >&2 echo "Error: No pre-commit on PATH. $hint"
-  exit 2
-fi
+for cmd in "$DEFAULT_PY" uv pre-commit; do
+  if ! type "$cmd"; then
+    >&2 echo "Error: No '$cmd' on PATH. $hint"
+    exit 1
+  fi
+done
 pre-commit install -f
 
-export VENV_BASE_DIR=".venv"
-mkdir -p "$VENV_BASE_DIR"
-
-export DEV_VENV="$VENV_BASE_DIR/dev"
-
-if ! test -d "$DEV_VENV"; then
-  "$DEV_PY" -m venv --upgrade-deps "$DEV_VENV"
-fi
-
-export DEV_PIP="$DEV_VENV/bin/pip"
-export DEV_PIP_SYNC="$DEV_VENV/bin/pip-sync"
-
-if ! test -e "$DEV_PIP_SYNC"; then
-  "$DEV_PIP" install pip-tools
-  test -e "$DEV_PIP_SYNC"
+export VENV_DIR=".venv"
+if ! test -d "$VENV_DIR"; then
+  uv venv --python="$DEFAULT_PY" "$VENV_DIR"
 fi
 
 declare -r req_sets="dev docs test"
-declare -r out_dir="dev-deps/$DEV_PY"
+declare -r out_dir="dev-deps/$DEFAULT_PY"
 mkdir -p "$out_dir"
 for i in $req_sets; do
   reqs_in="dev-deps/$i.in"
   reqs_out="$out_dir/$i.txt"
-  "$DEV_VENV/bin/pip-compile" --strip-extras --generate-hashes --reuse-hashes --allow-unsafe "$reqs_in" -o "$reqs_out"
+  uv pip compile --generate-hashes "$reqs_in" -o "$reqs_out"
 done
-"$DEV_PIP_SYNC" $out_dir/*.txt
+# TODO The following triggers https://github.com/astral-sh/uv/issues/1552
+# uv pip sync $out_dir/*.txt
+# so work around this as follows:
+declare -r reqs=("$out_dir"/*.txt)
+uv pip install "${reqs[@]/#/-r}"
 
-if ! "$DEV_PIP" show -qq bidict; then
-  "$DEV_PIP" install -e .
+# TODO Until https://github.com/astral-sh/uv/issues/1594 is fixed, we can't use the following:
+# if ! uv pip show -qq bidict; then
+# so work around this as follows:
+if ! uv pip freeze | grep -q ^bidict; then
+  uv pip install -e .
 fi
 
-echo "Development virtualenv initialized: ./$DEV_VENV"
-echo "To activate, run: source ./$DEV_VENV/bin/activate (or equivalent for your shell)"
+echo "Development virtualenv initialized: ./$VENV_DIR"
+echo "To activate, run: source ./$VENV_DIR/bin/activate (or equivalent for your shell)"
