Fix coverage with pytest-xdist, switch default py version to 3.12 (for coverage and development)
Coverage was not being correctly combined when running pytest-xdist with
more than one subprocess.

Also add new "coverage" tox env for locally running tests with coverage
more conveniently, and upgrade dev dependencies.

diff --git a/init_dev_env b/init_dev_env
--- a/init_dev_env
+++ b/init_dev_env
@@ -2,27 +2,57 @@
 
 set -euo pipefail
 
-if ! type python3.11; then
-  >&2 echo "No python3.11 on PATH. Hint: Use direnv + ./flake.nix to bootstrap a development environment"
+# Keep in sync with _default_py_minor_ver in ./tox.ini and ./upgrade-dev-dependencies:
+declare -r _default_py_minor_ver="12"
+export DEV_PY="python3.$_default_py_minor_ver"
+
+declare -r hint="Hint: Use direnv + ./flake.nix to bootstrap a development environment"
+
+if ! type "$DEV_PY"; then
+  >&2 echo "Error: No $DEV_PY on PATH. $hint"
   exit 1
 fi
 
-if ! test -d .venv; then
-  mkdir .venv
+if ! type pre-commit; then
+  >&2 echo "Error: No pre-commit on PATH. $hint"
+  exit 2
 fi
-if ! test -d .venv/dev; then
-  python3.11 -m venv --upgrade-deps .venv/dev
+pre-commit install -f
+
+export VENV_BASE_DIR=".venv"
+mkdir -p "$VENV_BASE_DIR"
+
+export DEV_VENV="$VENV_BASE_DIR/dev"
+
+if ! test -d "$DEV_VENV"; then
+  "$DEV_PY" -m venv --upgrade-deps "$DEV_VENV"
 fi
 
-if type pre-commit; then
-  pre-commit install -f
-else
-  >&2 echo "No pre-commit on PATH. Hint: Use direnv + ./flake.nix to bootstrap a development environment"
-  exit 1
+export DEV_PIP="$DEV_VENV/bin/pip"
+export DEV_PIP_SYNC="$DEV_VENV/bin/pip-sync"
+
+if ! test -e "$DEV_PIP_SYNC"; then
+  "$DEV_PIP" install pip-tools
+  test -e "$DEV_PIP_SYNC"
 fi
 
-# shellcheck disable=SC1091
-source .venv/dev/bin/activate
-type -p pip-sync || pip install pip-tools
-pip-sync dev-deps/python3.11/dev.txt dev-deps/python3.11/test.txt
-pip show -qq bidict || pip install -e .
+declare -r req_sets="dev docs test"
+declare -r out_dir="dev-deps/$DEV_PY"
+mkdir -p "$out_dir"
+for i in $req_sets; do
+  reqs_in="dev-deps/$i.in"
+  reqs_out="$out_dir/$i.txt"
+  if ! test -e "$reqs_out"; then
+    "$DEV_VENV/bin/pip-compile" --strip-extras --generate-hashes --reuse-hashes --allow-unsafe "$reqs_in" -o "$reqs_out"
+    test -e "$reqs_out"
+  fi
+done
+# shellcheck disable=SC2086
+"$DEV_PIP_SYNC" $out_dir/${req_sets// /.txt $out_dir/}.txt
+
+if ! "$DEV_PIP" show -qq bidict; then
+  "$DEV_PIP" install -e .
+fi
+
+echo "Development virtualenv initialized: ./$DEV_VENV"
+echo "To activate, run: source ./$DEV_VENV/bin/activate (or equivalent for your shell)"
diff --git a/upgrade-dev-dependencies b/upgrade-dev-dependencies
--- a/upgrade-dev-dependencies
+++ b/upgrade-dev-dependencies
@@ -17,20 +17,35 @@ log() {
 
 
 main() {
+  # Keep in sync with _default_py_minor_ver in ./tox.ini and ./init_dev_env:
+  declare -r _default_py_minor_ver="12"
+  export DEV_PY="python3.$_default_py_minor_ver"
+  if ! type "$DEV_PY"; then
+    log "Error: No $DEV_PY on PATH. Hint: Check ./init_dev_env and try again."
+    exit 1
+  fi
+  export DEV_VENV=".venv/dev"
+  if [ ! -e "$DEV_VENV/bin/$DEV_PY" ]; then
+    log "Error: No such file "$DEV_VENV/bin/$DEV_PY". Hint: Run ./init_dev_env and try again."
+    exit 2
+  fi
+  if ! type "pre-commit"; then
+    log "Error: pre-commit not found in PATH."
+    exit 3
+  fi
+
   local -r gitbranch=$(git branch --show-current)
   if [ "$gitbranch" = "deps" ] || [ "$gitbranch" = "dev" ]; then
     log "Already on branch '$gitbranch'"
   elif [ "$gitbranch" = "main" ]; then
     git checkout -b deps main
   else
-    log "On unsupported branch '$gitbranch'. Switch to 'main' and try again."
-    exit 1
+    log "Error: On unsupported branch '$gitbranch'. Switch to 'main' and try again."
+    exit 3
   fi
 
-
   log "Upgrading PyPI dependencies..."
-  local -r dev_py="python3.11"  # Main version used for development
-  local -r pip_compile="pip-compile --generate-hashes --reuse-hashes --upgrade --allow-unsafe"
+  local -r pip_compile="pip-compile --strip-extras --generate-hashes --reuse-hashes --upgrade --allow-unsafe"
   for py in python3.12 python3.11 python3.10 python3.9 python3.8 pypy3.10 pypy3.9; do
     local manage_deps_env=".venv/deps/$py"
     [ -e "$manage_deps_env" ] || $py -m venv "$manage_deps_env"
@@ -38,28 +53,28 @@ main() {
     "$manage_deps_env/bin/pip" install --upgrade pip-tools
     mkdir -pv "dev-deps/$py"
     $manage_deps_env/bin/$pip_compile dev-deps/test.in -o "dev-deps/$py/test.txt" >/dev/null
-    # Compile remaining layers just for our dev interpreter (3.11):
-    if [ "$py" = "$dev_py" ]; then
-      for i in docs lint dev; do
+    # Compile remaining layers just for our dev interpreter:
+    if [ "$py" = "$DEV_PY" ]; then
+      for i in docs dev; do
         $manage_deps_env/bin/$pip_compile "dev-deps/$i.in" -o "dev-deps/$py/$i.txt"
       done
     fi
   done
-  .venv/dev/bin/pip install --upgrade pip-tools
-  .venv/dev/bin/pip-sync dev-deps/$dev_py/{docs,lint,test,dev}.txt
-  .venv/dev/bin/pip install -e .
+  "$DEV_VENV/bin/pip" install --upgrade pip-tools
+  "$DEV_VENV/bin/pip-sync" dev-deps/$DEV_PY/{docs,test,dev}.txt
+  "$DEV_VENV/bin/pip" install -e .
   log "Upgrading PyPI dependencies: Done"
 
   log "Upgrading pre-commit hooks..."
-  .venv/dev/bin/pre-commit autoupdate
+  pre-commit autoupdate
   log "Upgrading pre-commit hooks: Testing..."
   git add .
-  .venv/dev/bin/pre-commit run --all-files
+  pre-commit run --all-files
 
   log "Done."
   log "Reminders:"
   log " - Check release notes of upgraded packages for anything that affects bidict."
-  log " - Run tests via 'tox' or by pushing to the 'deps' branch to ensure everything still works."
+  log " - Run tests via 'tox' (or on GitHub Actions by pushing to @jab's 'deps' branch) to ensure everything still works."
   log " - Check output for any new warnings, not just test failures."
 }
 
